spring.application.name=Sistema de atividades volutarios

server.port=${PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Logging
logging.level.root=INFO
logging.level.com.abcaa.sistema_atividades=INFO
logging.level.org.springframework=ERROR
logging.level.org.hibernate=WARN


# Flyway
spring.flyway.validate-on-migrate=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.web.encoding.charset=UTF-8
spring.web.encoding.force=true


certificate.organization.name=${CERTIFICATE_ORG_NAME}
certificate.organization.cnpj=${CERTIFICATE_ORG_CNPJ}
certificate.organization.city=${CERTIFICATE_ORG_CITY}
certificate.organization.state=${CERTIFICATE_ORG_STATE}

admin.name=${ADMIN_NAME:Administrador}
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}


# Performance
spring.main.lazy-initialization=true

# Hibernate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false


# Datasource
spring.datasource.hikari.initialization-fail-timeout=0

# Swagger OFF
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false


# ------evita travamento no Render-----

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2


server.compression.enabled=true
server.compression.mime-types=application/json,text/html,text/plain
server.compression.min-response-size=1024


server.tomcat.threads.max=20

#---------------reset password----------------
url.reset-password=${URL_RESET_PASSWORD}


#---------------email----------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_RESET_PASSWORD_VOLUNTEER}
spring.mail.password=${PASSWORD_RESET_PASSWORD_VOLUNTEER}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


