spring.application.name=Sistema de atividades volutarios

server.port=${PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.thymeleaf.encoding=UTF-8
spring.web.encoding.charset=UTF-8
spring.web.encoding.force=true
spring.web.encoding.enabled=true