spring.application.name=Sistema de atividades volutarios

server.port=${PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.root=INFO
logging.level.com.abcaa.sistema_atividades=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=WARN

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.thymeleaf.encoding=UTF-8
spring.web.encoding.charset=UTF-8
spring.web.encoding.force=true
spring.web.encoding.enabled=true

certificate.organization.name=${CERTIFICATE_ORG_NAME:Associacao Beneficiente e Cultural Amor em Acao}
certificate.organization.cnpj=${CERTIFICATE_ORG_CNPJ:54.794.100/0001-66}
certificate.organization.city=${CERTIFICATE_ORG_CITY:Quitandinha}
certificate.organization.state=${CERTIFICATE_ORG_STATE:PR}

admin.name=${ADMIN_NAME:Administrador}
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
