INSERT INTO tb_volunteer (name, email, department_id, user_type) VALUES
('Alan Maia da Silva', NULL, 1, 'VOLUNTEER'),
('Aline Oliveira Melo', NULL, 1, 'VOLUNTEER'),
('Ana Carolina Douro Azevedo', NULL, 1, 'VOLUNTEER'),
('Ana Luiza Rance de Lima Lira', NULL, 1, 'VOLUNTEER'),
('Ana Paula Santana Rocha', NULL, 1, 'VOLUNTEER'),
('Ananda Gabriela Cardoso da Silva', NULL, 1, 'VOLUNTEER'),
('Anderson Santos Oliveira', NULL, 1, 'VOLUNTEER'),
('Beatriz Oliveira de Faria', NULL, 1, 'VOLUNTEER'),
('Bianca Lima Santos', NULL, 1, 'VOLUNTEER'),
('Camilla Souza Santos', NULL, 1, 'VOLUNTEER'),
('David Oliveira de Melo Cavalcanti', NULL, 1, 'VOLUNTEER'),
('Fernanda Camacho de Souza Vieira da Silva', NULL, 1, 'VOLUNTEER'),
('Gabriel Augusto Santanna', NULL, 1, 'VOLUNTEER'),
('Gabriel Santos Teixeira', NULL, 1, 'VOLUNTEER'),
('Gabriely Rodrigues do Carmo', NULL, 1, 'VOLUNTEER'),
('Giovanna Ferreira José', NULL, 1, 'VOLUNTEER'),
('Gleidson Fagno da Conceição Pinheiro', NULL, 1, 'VOLUNTEER'),
('Graziela Freitas Araujo Duarte', NULL, 1, 'VOLUNTEER'),
('Heitor Roberto Sepulcri', NULL, 1, 'VOLUNTEER'),
('Isabela Araújo Santana Menezes', NULL, 1, 'VOLUNTEER'),
('Jairo Ribeiro Santos de Souza', NULL, 1, 'VOLUNTEER'),
('Jhonatan Hudson', NULL, 1, 'VOLUNTEER'),
('Jonas Lemes Bertoldo Scherer', NULL, 1, 'VOLUNTEER'),
('José Jefferson da Silva Vaz', NULL, 1, 'VOLUNTEER'),
('José Moisés Lopes da Silva', NULL, 1, 'VOLUNTEER'),
('Juliane de Jesus da Silva Souza', NULL, 1, 'VOLUNTEER'),
('Kalleb Ribeiro Machado', NULL, 1, 'VOLUNTEER'),
('Ketlyn Soares da Silva', NULL, 1, 'VOLUNTEER'),
('Lairton Santos de Araújo', NULL, 1, 'VOLUNTEER'),
('Laísa Barbosa de Pinho', NULL, 1, 'VOLUNTEER'),
('Laryssa Moreira Mendes', NULL, 1, 'VOLUNTEER'),
('Leticia Costa Lopes', NULL, 1, 'VOLUNTEER'),
('Letícia Pardinho de Paula', NULL, 1, 'VOLUNTEER'),
('Luciano da Silva Martins', NULL, 1, 'VOLUNTEER'),
('Luis Paulo Guimarães Lira', NULL, 1, 'VOLUNTEER'),
('Luiz Alberto Lucio da Silva', NULL, 1, 'VOLUNTEER'),
('Maiara de França Santos', NULL, 1, 'VOLUNTEER'),
('Marcelo Abreu Artes', NULL, 1, 'VOLUNTEER'),
('Maria Isabel Sales Peixoto', NULL, 1, 'VOLUNTEER'),
('Matheus da Guarda', NULL, 1, 'VOLUNTEER'),
('Matheus Guida Rocha', NULL, 1, 'VOLUNTEER'),
('Matheus Jesus Santos da Guarda', NULL, 1, 'VOLUNTEER'),
('Monique Paula Félix da Silva Gomes', NULL, 1, 'VOLUNTEER'),
('Natascha Cazé Antônio', NULL, 1, 'VOLUNTEER'),
('Nicole de Lima', NULL, 1, 'VOLUNTEER'),
('Paula Carina Rodrigues Pereira Sabino', NULL, 1, 'VOLUNTEER'),
('Rebeca Gonçalves Bezerra', NULL, 1, 'VOLUNTEER'),
('Rejane Priscila Ribeiro da Silva', NULL, 1, 'VOLUNTEER'),
('Robson Mesquita', NULL, 1, 'VOLUNTEER'),
('Vicente Kayodê Guedes Rodrigues dos Santos', NULL, 1, 'VOLUNTEER'),
('Vinicius Gonzalez de Freitas', NULL, 1, 'VOLUNTEER'),
('Vinicius Lima Oliveira', NULL, 1, 'VOLUNTEER');